from typing import Protocol, Sequence, TypeVar

T = TypeVar("T")


class TerminalUi(Protocol):
    def choose(self, message: str, choices: Sequence[tuple[str, T]]) -> T | None: ...

    def ask_text(self, message: str) -> str | None: ...

    def print(self, message: str = "") -> None: ...

    def clear(self) -> None: ...

    def pause(self, message: str = "Press any key to continue") -> None: ...
